import type { EditorAction } from "./editor.js";

export interface Challenge {
  id: string;
  title: string;
  instruction: string;
  hint: string;
  start: string;
  startCursor: number;
  target: string;
  targetCursor: number;
  focus: EditorAction;
  focusLabel: string;
  idealKeys: number;
}

const length = (value: string): number => Array.from(value).length;

export const challenges: Challenge[] = [
  {
    id: "line-start",
    title: "Get to the start",
    instruction: "Prefix the command with `sudo `.",
    hint: "Ctrl+A jumps to the beginning of the line.",
    start: "systemctl restart api",
    startCursor: length("systemctl restart api"),
    target: "sudo systemctl restart api",
    targetCursor: length("sudo "),
    focus: "line-start",
    focusLabel: "Ctrl+A",
    idealKeys: 2,
  },
  {
    id: "line-end",
    title: "Get to the end",
    instruction: "Append ` --short` to the command.",
    hint: "Ctrl+E jumps to the end of the line.",
    start: "git status",
    startCursor: 0,
    target: "git status --short",
    targetCursor: length("git status --short"),
    focus: "line-end",
    focusLabel: "Ctrl+E",
    idealKeys: 2,
  },
  {
    id: "char-left",
    title: "One character back",
    instruction: "Move left once, then insert `t`.",
    hint: "Ctrl+B moves backward by one character.",
    start: "git staus",
    startCursor: 8,
    target: "git status",
    targetCursor: 8,
    focus: "move-char-left",
    focusLabel: "Ctrl+B",
    idealKeys: 2,
  },
  {
    id: "char-right",
    title: "One character forward",
    instruction: "Move right once, then insert `t`.",
    hint: "Ctrl+F moves forward by one character.",
    start: "git staus",
    startCursor: 6,
    target: "git status",
    targetCursor: 8,
    focus: "move-char-right",
    focusLabel: "Ctrl+F",
    idealKeys: 2,
  },
  {
    id: "word-left",
    title: "Jump back a word",
    instruction: "Move to the start of `feature`, then insert `switch `.",
    hint: "Alt+B or Ctrl+Left moves backward by one word.",
    start: "git feature",
    startCursor: length("git feature"),
    target: "git switch feature",
    targetCursor: length("git switch "),
    focus: "move-word-left",
    focusLabel: "Alt+B / Ctrl+Left",
    idealKeys: 2,
  },
  {
    id: "word-right",
    title: "Jump forward a word",
    instruction: "Move past `login`, then insert ` --verbose`.",
    hint: "Alt+F or Ctrl+Right moves forward by one word.",
    start: "git login --force",
    startCursor: length("git "),
    target: "git login --verbose --force",
    targetCursor: length("git login --verbose"),
    focus: "move-word-right",
    focusLabel: "Alt+F / Ctrl+Right",
    idealKeys: 2,
  },
  {
    id: "kill-to-end",
    title: "Clear to the end",
    instruction: "Remove `--short` while keeping `git status `.",
    hint: "Ctrl+K kills everything from the cursor to the end.",
    start: "git status --short",
    startCursor: length("git status "),
    target: "git status ",
    targetCursor: length("git status "),
    focus: "kill-to-end",
    focusLabel: "Ctrl+K",
    idealKeys: 1,
  },
  {
    id: "kill-to-start",
    title: "Clear to the start",
    instruction: "Delete the whole temporary command.",
    hint: "Ctrl+U kills everything from the start to the cursor.",
    start: "temporary git status",
    startCursor: length("temporary git status"),
    target: "",
    targetCursor: 0,
    focus: "kill-to-start",
    focusLabel: "Ctrl+U",
    idealKeys: 1,
  },
  {
    id: "kill-previous-word",
    title: "Kill the previous word",
    instruction: "Remove the word `message`.",
    hint: "Ctrl+W kills the previous word and its separating space.",
    start: "git commit message",
    startCursor: length("git commit message"),
    target: "git commit",
    targetCursor: length("git commit"),
    focus: "kill-previous-word",
    focusLabel: "Ctrl+W",
    idealKeys: 1,
  },
  {
    id: "kill-next-word",
    title: "Kill the next word",
    instruction: "From after `git `, remove `commit `.",
    hint: "Alt+D kills the next word and its following space.",
    start: "git commit message",
    startCursor: length("git "),
    target: "git message",
    targetCursor: length("git "),
    focus: "kill-next-word",
    focusLabel: "Alt+D",
    idealKeys: 1,
  },
  {
    id: "yank",
    title: "Yank it back",
    instruction: "Kill `--short`, then restore it with one yank.",
    hint: "Ctrl+Y inserts the most recently killed text.",
    start: "git status --short",
    startCursor: length("git status "),
    target: "git status --short",
    targetCursor: length("git status --short"),
    focus: "yank",
    focusLabel: "Ctrl+Y",
    idealKeys: 2,
  },
  {
    id: "transpose",
    title: "Transpose a typo",
    instruction: "Fix `stauts` by transposing the two middle letters.",
    hint: "Ctrl+T swaps the character before and at the cursor.",
    start: "git stauts",
    startCursor: 8,
    target: "git status",
    targetCursor: 9,
    focus: "transpose",
    focusLabel: "Ctrl+T",
    idealKeys: 1,
  },
  {
    id: "delete-character",
    title: "Delete under the cursor",
    instruction: "Delete the extra `t` under the cursor.",
    hint: "Ctrl+D deletes the character at the cursor.",
    start: "git sttatus",
    startCursor: 6,
    target: "git status",
    targetCursor: 6,
    focus: "delete-next-char",
    focusLabel: "Ctrl+D",
    idealKeys: 1,
  },
];
