import type { EditorAction } from "./editor.js";

export interface Challenge {
  id: string;
  title: string;
  instructions: string[];
  hint: string;
  start: string;
  startCursor: number;
  target: string;
  targetCursor: number;
  focus: EditorAction;
  focusLabel: string;
  focusDescription: string;
  /** Minimum physical keyboard presses, excluding Enter used to submit. */
  idealKeys: number;
}

const length = (value: string): number => Array.from(value).length;

export const challenges: Challenge[] = [
  {
    id: "line-start",
    title: "Get to the start",
    instructions: ["Prefix the command with sudo followed by a space."],
    hint: "Ctrl+A jumps to the beginning of the line.",
    start: "systemctl restart api",
    startCursor: length("systemctl restart api"),
    target: "sudo systemctl restart api",
    targetCursor: length("sudo "),
    focus: "line-start",
    focusLabel: "Ctrl+A",
    focusDescription: "start of line",
    idealKeys: 1 + length("sudo "),
  },
  {
    id: "line-end",
    title: "Get to the end",
    instructions: ["Append --short to the command."],
    hint: "Ctrl+E jumps to the end of the line.",
    start: "git status",
    startCursor: 0,
    target: "git status --short",
    targetCursor: length("git status --short"),
    focus: "line-end",
    focusLabel: "Ctrl+E",
    focusDescription: "end of line",
    idealKeys: 1 + length(" --short"),
  },
  {
    id: "char-left",
    title: "One character back",
    instructions: ["Move left once.", "Insert t."],
    hint: "Ctrl+B moves backward by one character.",
    start: "git staus",
    startCursor: 8,
    target: "git status",
    targetCursor: 8,
    focus: "move-char-left",
    focusLabel: "Ctrl+B",
    focusDescription: "move left",
    idealKeys: 2,
  },
  {
    id: "char-right",
    title: "One character forward",
    instructions: ["Move right once.", "Insert t."],
    hint: "Ctrl+F moves forward by one character.",
    start: "git staus",
    startCursor: 6,
    target: "git status",
    targetCursor: 8,
    focus: "move-char-right",
    focusLabel: "Ctrl+F",
    focusDescription: "move right",
    idealKeys: 2,
  },
  {
    id: "word-left",
    title: "Jump back a word",
    instructions: ["Move to the start of feature.", "Insert switch followed by a space."],
    hint: "Alt+B or Ctrl+Left moves backward by one word.",
    start: "git feature",
    startCursor: length("git feature"),
    target: "git switch feature",
    targetCursor: length("git switch "),
    focus: "move-word-left",
    focusLabel: "Alt+B / Ctrl+Left",
    focusDescription: "previous word",
    idealKeys: 1 + length("switch "),
  },
  {
    id: "word-right",
    title: "Jump forward a word",
    instructions: ["Move past login.", "Insert --verbose with a leading space."],
    hint: "Alt+F or Ctrl+Right moves forward by one word.",
    start: "git login --force",
    startCursor: length("git "),
    target: "git login --verbose --force",
    targetCursor: length("git login --verbose"),
    focus: "move-word-right",
    focusLabel: "Alt+F / Ctrl+Right",
    focusDescription: "next word",
    idealKeys: 1 + length(" --verbose"),
  },
  {
    id: "kill-to-end",
    title: "Clear to the end",
    instructions: ["Remove --short while keeping git status and its trailing space."],
    hint: "Ctrl+K kills everything from the cursor to the end.",
    start: "git status --short",
    startCursor: length("git status "),
    target: "git status ",
    targetCursor: length("git status "),
    focus: "kill-to-end",
    focusLabel: "Ctrl+K",
    focusDescription: "clear to end",
    idealKeys: 1,
  },
  {
    id: "kill-to-start",
    title: "Clear to the start",
    instructions: ["Delete the whole temporary command."],
    hint: "Ctrl+U kills everything from the start to the cursor.",
    start: "temporary git status",
    startCursor: length("temporary git status"),
    target: "",
    targetCursor: 0,
    focus: "kill-to-start",
    focusLabel: "Ctrl+U",
    focusDescription: "clear to start",
    idealKeys: 1,
  },
  {
    id: "kill-previous-word",
    title: "Kill the previous word",
    instructions: ["Remove the word message."],
    hint: "Ctrl+W kills the previous word and its separating space.",
    start: "git commit message",
    startCursor: length("git commit message"),
    target: "git commit",
    targetCursor: length("git commit"),
    focus: "kill-previous-word",
    focusLabel: "Ctrl+W",
    focusDescription: "delete previous word",
    idealKeys: 1,
  },
  {
    id: "kill-next-word",
    title: "Kill the next word",
    instructions: ["From after git, remove commit and its trailing space."],
    hint: "Alt+D kills the next word and its following space.",
    start: "git commit message",
    startCursor: length("git "),
    target: "git message",
    targetCursor: length("git "),
    focus: "kill-next-word",
    focusLabel: "Alt+D",
    focusDescription: "delete next word",
    idealKeys: 1,
  },
  {
    id: "yank",
    title: "Yank it back",
    instructions: ["Kill --short.", "Restore it with one yank."],
    hint: "Ctrl+Y inserts the most recently killed text.",
    start: "git status --short",
    startCursor: length("git status "),
    target: "git status --short",
    targetCursor: length("git status --short"),
    focus: "yank",
    focusLabel: "Ctrl+Y",
    focusDescription: "restore last kill",
    idealKeys: 2,
  },
  {
    id: "transpose",
    title: "Transpose a typo",
    instructions: ["Fix stauts by transposing the two middle letters."],
    hint: "Ctrl+T swaps the character before and at the cursor.",
    start: "git stauts",
    startCursor: 8,
    target: "git status",
    targetCursor: 9,
    focus: "transpose",
    focusLabel: "Ctrl+T",
    focusDescription: "swap characters",
    idealKeys: 1,
  },
  {
    id: "delete-character",
    title: "Delete under the cursor",
    instructions: ["Delete the extra t under the cursor."],
    hint: "Ctrl+D deletes the character at the cursor.",
    start: "git sttatus",
    startCursor: 6,
    target: "git status",
    targetCursor: 6,
    focus: "delete-next-char",
    focusLabel: "Ctrl+D",
    focusDescription: "delete next character",
    idealKeys: 1,
  },

  // Repeat the core shortcuts in different command-line contexts to build
  // muscle memory instead of tying each shortcut to one fixed sentence.
  {
    id: "line-start-prefix",
    title: "Prefix another command",
    instructions: ["Prefix the test command with env APP_ENV=test followed by a space."],
    hint: "Ctrl+A jumps to the beginning of the line.",
    start: "npm test -- --runInBand",
    startCursor: length("npm test -- --runInBand"),
    target: "env APP_ENV=test npm test -- --runInBand",
    targetCursor: length("env APP_ENV=test "),
    focus: "line-start",
    focusLabel: "Ctrl+A",
    focusDescription: "start of line",
    idealKeys: 1 + length("env APP_ENV=test "),
  },
  {
    id: "line-end-redirect",
    title: "Append a redirect",
    instructions: ["Append 2>&1 to the test command with a leading space."],
    hint: "Ctrl+E jumps to the end of the line.",
    start: "npm test",
    startCursor: 0,
    target: "npm test 2>&1",
    targetCursor: length("npm test 2>&1"),
    focus: "line-end",
    focusLabel: "Ctrl+E",
    focusDescription: "end of line",
    idealKeys: 1 + length(" 2>&1"),
  },
  {
    id: "char-left-missing-letter",
    title: "Repair from one step back",
    instructions: ["Move left once.", "Insert n."],
    hint: "Ctrl+B moves backward by one character.",
    start: "npm istall",
    startCursor: length("npm is"),
    target: "npm install",
    targetCursor: length("npm in"),
    focus: "move-char-left",
    focusLabel: "Ctrl+B",
    focusDescription: "move left",
    idealKeys: 2,
  },
  {
    id: "char-right-missing-letter",
    title: "Repair one character forward",
    instructions: ["Move right once.", "Insert c."],
    hint: "Ctrl+F moves forward by one character.",
    start: "git chekout",
    startCursor: length("git ch"),
    target: "git checkout",
    targetCursor: length("git chec"),
    focus: "move-char-right",
    focusLabel: "Ctrl+F",
    focusDescription: "move right",
    idealKeys: 2,
  },
  {
    id: "word-left-option",
    title: "Insert before the final argument",
    instructions: ["Move to the start of production.", "Insert --dry-run followed by a space."],
    hint: "Alt+B or Ctrl+Left moves backward by one word.",
    start: "git deploy production",
    startCursor: length("git deploy production"),
    target: "git deploy --dry-run production",
    targetCursor: length("git deploy --dry-run "),
    focus: "move-word-left",
    focusLabel: "Alt+B / Ctrl+Left",
    focusDescription: "previous word",
    idealKeys: 1 + length("--dry-run "),
  },
  {
    id: "word-right-option",
    title: "Insert after the first command",
    instructions: ["Move past docker.", "Insert --rm with a leading space."],
    hint: "Alt+F or Ctrl+Right moves forward by one word.",
    start: "docker run alpine",
    startCursor: 0,
    target: "docker --rm run alpine",
    targetCursor: length("docker --rm"),
    focus: "move-word-right",
    focusLabel: "Alt+F / Ctrl+Right",
    focusDescription: "next word",
    idealKeys: 1 + length(" --rm"),
  },
  {
    id: "kill-to-end-options",
    title: "Clear several trailing options",
    instructions: ["Remove the options after git commit while keeping its trailing space."],
    hint: "Ctrl+K kills everything from the cursor to the end.",
    start: "git commit --amend --no-edit",
    startCursor: length("git commit "),
    target: "git commit ",
    targetCursor: length("git commit "),
    focus: "kill-to-end",
    focusLabel: "Ctrl+K",
    focusDescription: "clear to end",
    idealKeys: 1,
  },
  {
    id: "kill-to-start-prefix",
    title: "Clear a command prefix",
    instructions: ["Remove sudo while keeping the rest of the command."],
    hint: "Ctrl+U kills everything from the start to the cursor.",
    start: "sudo systemctl restart api",
    startCursor: length("sudo "),
    target: "systemctl restart api",
    targetCursor: 0,
    focus: "kill-to-start",
    focusLabel: "Ctrl+U",
    focusDescription: "clear to start",
    idealKeys: 1,
  },
  {
    id: "kill-previous-option",
    title: "Kill a previous option",
    instructions: ["From after --amend, remove that option and its separating space."],
    hint: "Ctrl+W kills the previous word and its separating space.",
    start: "git commit --amend message",
    startCursor: length("git commit --amend"),
    target: "git commit message",
    targetCursor: length("git commit"),
    focus: "kill-previous-word",
    focusLabel: "Ctrl+W",
    focusDescription: "delete previous word",
    idealKeys: 1,
  },
  {
    id: "kill-next-prefix",
    title: "Kill the next word",
    instructions: ["From the start, remove sudo and its following space."],
    hint: "Alt+D kills the next word and its following space.",
    start: "sudo git status",
    startCursor: 0,
    target: "git status",
    targetCursor: 0,
    focus: "kill-next-word",
    focusLabel: "Alt+D",
    focusDescription: "delete next word",
    idealKeys: 1,
  },
  {
    id: "yank-command",
    title: "Yank a whole command",
    instructions: ["Kill the command.", "Restore it with one yank."],
    hint: "Ctrl+Y inserts the most recently killed text.",
    start: "docker compose up --detach",
    startCursor: length("docker compose up --detach"),
    target: "docker compose up --detach",
    targetCursor: length("docker compose up --detach"),
    focus: "yank",
    focusLabel: "Ctrl+Y",
    focusDescription: "restore last kill",
    idealKeys: 2,
  },
  {
    id: "transpose-at-end",
    title: "Transpose at the end",
    instructions: ["Fix statsu by transposing its final two letters."],
    hint: "Ctrl+T swaps the character before and at the cursor.",
    start: "git statsu",
    startCursor: length("git statsu"),
    target: "git status",
    targetCursor: length("git status"),
    focus: "transpose",
    focusLabel: "Ctrl+T",
    focusDescription: "swap characters",
    idealKeys: 1,
  },
  {
    id: "delete-option-character",
    title: "Delete an extra option character",
    instructions: ["Delete the extra dash under the cursor."],
    hint: "Ctrl+D deletes the character at the cursor.",
    start: "git --status",
    startCursor: length("git "),
    target: "git -status",
    targetCursor: length("git "),
    focus: "delete-next-char",
    focusLabel: "Ctrl+D",
    focusDescription: "delete next character",
    idealKeys: 1,
  },
];
